### PR TITLE
Unclack.app initial commit.

### PR DESCRIPTION
**Pull request by jutonium**
Thanks @a-vogel for preparing the recipe with recipe robot.

This is a recipe for Unclack.app, an app that suppresses clicking and clacking sounds during video conferences. Especially those of a MacBook built-in keyboard.

### CODE REVIEW

**Comment by choules** [comment]
Is having an app icon next to the recipe a common practice? Haven't seen it before...

**Comment by choules** [comment]
I have added the automated generation of minimum_os_version for the Munki recipe.

**Review by choules — CHANGES_REQUESTED** [review]
Please remove the [app icon](Unclack/Unclack.png), for legal reasons. We should make sure that it is not included in any commits, as well. Perhaps we will do a squash and merge.

And: Please have a look at my modifications to the munki recipe. All recipes are working fine in my testing environment.

**Comment by a-vogel** [comment]
Override was created and is working (installation/uninstallation). PNG has been removed.

**Pull request merged**
